version: "3.8"

services:
    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - database:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3307:3306"
        networks:
            - network
        restart:
            'always'
    php:
        build:
            context: ./infrastructure/php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./src:/var/www/app:cached
        ports:
            - "9001:9000"
        networks:
            - network
        depends_on:
            - mysql
        restart:
            'always'
    nginx:
        build:
            context: ./infrastructure/nginx
        volumes:
            - ./src:/var/www/app:cached
        ports:
            - "8001:80"
        networks:
            - network
        restart:
            'always'

volumes:
    database:

networks:
    network:
